import java.util.Scanner;

public class Main {
    public static void main(String[] args) {
        // from Linux:
        System.out.println("From Linux: Hello world!");
        //from Mac
        System.out.println("From MacOS: Hello world!");
        //from Windows:
        System.out.println("from Windows 11: Hello world!");

        // merged from FeatureUI branch:
        Scanner sc = new Scanner(System.in);

        System.out.print("What would you like to say? ");
        String input = sc.nextLine();
        System.out.println();

        for(char c : input.toCharArray()){
            System.out.print(c + " ");
        }
        // Staging area enabled:
        System.out.println("\n\nTo set up Staging in IntelliJ, go to Files>Settings>version Control>Git, \n" +
                "or press ctrl+alt+s. Under 'Commit' section, check the box, \"Enable staging area\"\n");

        // To stage or not stage generated module files?
        System.out.println(
                "Stack Overflow says it's best not to store files generated by the IDE \n" +
                "in order to make projects as IDE-agonsitc as possible. But what if the \n " +
                "participants of the project all use IntelliJ? \n" +
                "Here, I am committing only the changed file in /src, Main.java.\n" +
                "It's worth noting that when the Staging area is not enabled, IntelliJ \n" +
                "categorizes generated files in 'unversionied'. I can choose to commit \n" +
                "them if I like.");
    }
}